import Head from 'next/head'
import { Inter } from '@next/font/google'
import { Text } from "@nextui-org/react";
import QNA from './../components/QNA';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>QNA via TensorflowJS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        {/* 
          Had to add script based import as suggested here: https://github.com/tensorflow/tfjs/issues/3352#issuecomment-771094460
        */}
        <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-core"></script>
        <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-converter"></script>
        <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-webgl"></script>
        <script src="https://cdn.jsdelivr.net/npm/@tensorflow-models/handpose"></script>
      </Head>
      <main>
        <div className='grid place-items-center'>
          <Text h1 size={60} css={{ textGradient: "45deg, $blue600 -20%, $pink600 50%", }} weight="bold" >
            Question Answer via
          </Text>
          <Text h1 size={40} css={{ textGradient: "45deg, $yellow600 -20%, $red600 100%", }} weight="bold" >
            Tensorflow JS
          </Text>
        </div>
        <div className='mt-3'>
            <QNA />
          </div>
      </main>
    </>
  )
}
